# Generated by Django 6.0 on 2026-01-23 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_respectful', models.BooleanField(default=False, verbose_name='Поважна причина')),
            ],
            options={
                'verbose_name': 'Причина пропуску',
                'verbose_name_plural': 'Причини пропусків',
                'db_table': 'absence_reasons',
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип заняття (Лекція/Практика)')),
                ('weight_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Вплив на оцінку (%)')),
            ],
            options={
                'verbose_name': 'Тип оцінювання',
                'verbose_name_plural': 'Типи оцінювання',
                'db_table': 'evaluation_types',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва групи')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'db_table': 'study_groups',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва предмету')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studygroup', verbose_name='Група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Навантаження викладача',
                'verbose_name_plural': 'Навантаження викладачів',
                'db_table': 'teaching_assignments',
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведення')),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема заняття')),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.evaluationtype', verbose_name='Тип заняття')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachingassignment')),
            ],
            options={
                'verbose_name': 'Проведене заняття',
                'verbose_name_plural': 'Проведені заняття',
                'db_table': 'lesson_sessions',
                'ordering': ['-date', 'lesson_number'],
                'unique_together': {('assignment', 'date', 'lesson_number')},
            },
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_types', to='main.teachingassignment'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('teacher', 'Викладач'), ('student', 'Студент')], max_length=10, verbose_name='Роль')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.studygroup')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'tbl_users',
            },
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Викладач'),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('subject', 'teacher', 'group')},
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.absencereason', verbose_name='Пропуск')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.lessonsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'verbose_name': 'Успішність студента',
                'verbose_name_plural': 'Успішність студентів',
                'db_table': 'student_performance',
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота'), (7, 'Неділя')], verbose_name='День тижня')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='Номер пари')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachingassignment', verbose_name='Дисципліна')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклад',
                'db_table': 'weekly_schedule',
                'unique_together': {('assignment', 'day_of_week', 'lesson_number')},
            },
        ),
    ]
