# Generated by Django 6.0.1 on 2026-02-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='new_lesson',
        ),
        migrations.DeleteModel(
            name='LessonSession',
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
