# Generated by Django 6.0.1 on 2026-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_studentperformance_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Аудиторія'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Аудиторія'),
        ),
    ]
