# Generated by Django 6.0 on 2026-02-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_studentperformance_comment_buildingaccesslog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together={('group', 'day_of_week', 'lesson_number')},
        ),
    ]
