# Generated by Django 6.0.1 on 2026-02-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lesson_classroom_scheduletemplate_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва/Номер')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Корпус')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Місткість')),
            ],
            options={
                'verbose_name': 'Аудиторія',
                'verbose_name_plural': 'Аудиторії',
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва шкали')),
            ],
            options={
                'verbose_name': 'Шкала оцінювання',
                'verbose_name_plural': 'Шкали оцінювання',
                'db_table': 'grading_scales',
            },
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='grade',
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_points',
            field=models.PositiveIntegerField(default=5, verbose_name='Макс. балів'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер пари'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Набрані бали'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='duration_minutes',
            field=models.IntegerField(default=80, verbose_name='Тривалість (хв)'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='valid_from',
            field=models.DateField(auto_now_add=True, verbose_name='Діє з'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom', verbose_name='Аудиторія'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom', verbose_name='Аудиторія'),
        ),
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Оцінка (словом/буквою)')),
                ('min_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Мінімальний бал')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='main.gradingscale')),
            ],
            options={
                'verbose_name': 'Правило оцінювання',
                'verbose_name_plural': 'Правила оцінювання',
                'db_table': 'grade_rules',
                'ordering': ['-min_points'],
            },
        ),
    ]
